### PR TITLE
Refresh Token

### PR DESCRIPTION
**Pull request by jakebasile**
I added the ability to use a refresh token to get a new access token. I know this isn't widely supported, but it is part of the spec.

I wasn't really sure how to add any tests for this, but I have tested it manually with the Salesforce OAuth provider.

### CODE REVIEW

**Comment by demianbrecht** [comment]
Thanks for the fork/request. I've grabbed it and am working on testing it with Google (who does use refresh tokens). Definitely an oversight on my part.

**Comment by jakebasile** [comment]
Great. Let me know if there are any issues.

**Comment by demianbrecht** [comment]
After sleeping on it and remember what I was thinking when I originally wrote this, I've gone a bit of a different way and added the refresh token handling to request_token. The functionality was already 90% there (grant_type was already an arg of request_token), it just needed a little massaging.

I've tested it with Google (the only provider I know of that has implemented the refresh token functionality) and all seems to work as detailed in the spec.

I've added you to the newly created "thanks" list for pointing out the oversight.

**Comment by jakebasile** [comment]
That's a good solution. Thanks!

**Pull request closed without merging**
